### PR TITLE
feat: add account:describe command

### PR DESCRIPTION
**Pull request by zero1ne-dev**

### CODE REVIEW

**Comment by junbeomlee** [comment]
plz rename feat to docs

**Comment by zero1ne-dev** [comment]
apiKey -> clientId

**Review by zeroFruit — DISMISSED** [review]
lgtm

**Review by zeroFruit — COMMENTED** [review]
test failed

**Review by zeroFruit — APPROVED** [review]
lgtm now

**Review by junbeomlee — APPROVED** [review]

**Review by junbeomlee — APPROVED** [review]

**Pull request merged**
