### PR TITLE
feat: add autocomplete support

### PR DESCRIPTION
**Pull request by HaruHuey**
auto autocomplete support

### CODE REVIEW

**Comment by Nipol** [comment]
A test case is required because additional operation of the library cannot be expected.

**Comment by zero1ne-dev** [comment]
I would like to make two suggestions.

1. Please add test cases for the new feature.
2. Make a script to run the autocomplete function.

**Comment by zero1ne-dev** [comment]
@HaruHuey Plz rebase this branch.

**Comment by zero1ne-dev** [comment]
fixed at #104

**Pull request closed without merging**
